import json

canonical_names = {
    1001: ("スペシャルウィーク", "Special Week"),
    1002: ("サイレンススズカ", "Silence Suzuka"),
    1003: ("トウカイテイオー", "Tokai Teio"),
    1004: ("マルゼンスキー", "Maruzensky"),
    1005: ("フジキセキ", "Fuji Kiseki"),
    1006: ("オグリキャップ", "Oguri Cap"),
    1007: ("ゴールドシップ", "Gold Ship"),
    1008: ("ウオッカ", "Vodka"),
    1009: ("ダイワスカーレット", "Daiwa Scarlet"),
    1010: ("タイキシャトル", "Taiki Shuttle"),
    1011: ("グラスワンダー", "Grass Wonder"),
    1012: ("ヒシアマゾン", "Hishi Amazon"),
    1013: ("メジロマックイーン", "Mejiro McQueen"),
    1014: ("エルコンドルパサー", "El Condor Pasa"),
    1015: ("テイエムオペラオー", "TM Opera O"),
    1016: ("ナリタブライアン", "Narita Brian"),
    1017: ("シンボリルドルフ", "Symboli Rudolf"),
    1018: ("エアグルーヴ", "Air Groove"),
    1019: ("アグネスデジタル", "Agnes Digital"),
    1020: ("セイウンスカイ", "Seiun Sky"),
    1021: ("タマモクロス", "Tamamo Cross"),
    1022: ("ファインモーション", "Fine Motion"),
    1023: ("ビワハヤヒデ", "Biwa Hayahide"),
    1024: ("マヤノトップガン", "Mayano Top Gun"),
    1025: ("マンハッタンカフェ", "Manhattan Cafe"),
    1026: ("ミホノブルボン", "Mihono Bourbon"),
    1027: ("メジロライアン", "Mejiro Ryan"),
    1028: ("ヒシアケボノ", "Hishi Akebono"),
    1029: ("ユキノビジン", "Yukino Bijin"),
    1030: ("ライスシャワー", "Rice Shower"),
    1031: ("アイネスフウジン", "Ines Fujin"),
    1032: ("アグネスタキオン", "Agnes Tachyon"),
    1033: ("アドマイヤベガ", "Admire Vega"),
    1034: ("イナリワン", "Inari One"),
    1035: ("ウイニングチケット", "Winning Ticket"),
    1036: ("エアシャカール", "Air Shakur"),
    1037: ("エイシンフラッシュ", "Eishin Flash"),
    1038: ("カレンチャン", "Curren Chan"),
    1039: ("カワカミプリンセス", "Kawakami Princess"),
    1040: ("ゴールドシチー", "Gold City"),
    1041: ("サクラバクシンオー", "Sakura Bakushin O"),
    1042: ("シーキングザパール", "Seeking the Pearl"),
    1043: ("シンコウウインディ", "Shinko Windy"),
    1044: ("スイープトウショウ", "Sweep Tosho"),
    1045: ("スーパークリーク", "Super Creek"),
    1046: ("スマートファルコン", "Smart Falcon"),
    1047: ("ゼンノロブロイ", "Zenno Rob Roy"),
    1048: ("トーセンジョーダン", "Tosen Jordan"),
    1049: ("ナカヤマフェスタ", "Nakayama Festa"),
    1050: ("ナリタタイシン", "Narita Taishin"),
    1051: ("ニシノフラワー", "Nishino Flower"),
    1052: ("ハルウララ", "Haru Urara"),
    1053: ("バンブーメモリー", "Bamboo Memory"),
    1054: ("ビコーペガサス", "Biko Pegasus"),
    1055: ("マーベラスサンデー", "Marvelous Sunday"),
    1056: ("マチカネフクキタル", "Matikanefukukitaru"),
    1057: ("ミスターシービー", "Mr. C.B."),
    1058: ("メイショウドトウ", "Meisho Doto"),
    1059: ("メジロドーベル", "Mejiro Dober"),
    1060: ("ナイスネイチャ", "Nice Nature"),
    1061: ("キングヘイロー", "King Halo"),
    1062: ("マチカネタンホイザ", "Matikanetannhauser"),
    1063: ("イクノディクタス", "Ikuno Dictus"),
    1064: ("メジロパーマー", "Mejiro Palmer"),
    1065: ("ダイタクヘリオス", "Daitaku Helios"),
    1066: ("ツインターボ", "Twin Turbo"),
    1067: ("サトノダイヤモンド", "Satono Diamond"),
    1068: ("キタサンブラック", "Kitasan Black"),
    1069: ("サクラチヨノオー", "Sakura Chiyono O"),
    1070: ("シリウスシンボリ", "Sirius Symboli"),
    1071: ("メジロアルダン", "Mejiro Ardan"),
    1072: ("ヤエノムテキ", "Yaeno Muteki"),
    1073: ("ツルマルツヨシ", "Tsurumaru Tsuyoshi"),
    1074: ("メジロブライト", "Mejiro Bright"),
    1075: ("デアリングタクト", "Daring Tact"),
    1076: ("サクラローレル", "Sakura Laurel"),
    1077: ("ナリタトップロード", "Narita Top Road"),
    1078: ("ヤマニンゼファー", "Yamanin Zephyr"),
    1079: ("フリオーソ", "Furioso"),
    1080: ("トランセンド", "Transcend"),
    1081: ("エスポワールシチー", "Espoir City"),
    1082: ("ノースフライト", "North Flight"),
    1083: ("シンボリクリスエス", "Symboli Kris S"),
    1084: ("タニノギムレット", "Tanino Gimlet"),
    1085: ("ダイイチルビー", "Daiichi Ruby"),
    1086: ("メジロラモーヌ", "Mejiro Ramonu"),
    1087: ("アストンマーチャン", "Aston Machan"),
    1088: ("サトノクラウン", "Satono Crown"),
    1089: ("シュヴァルグラン", "Cheval Grand"),
    1090: ("ヴィルシーナ", "Verxina"),
    1091: ("ヴィブロス", "Vivlos"),
    1092: ("ダンツフレーム", "Dantsu Flame"),
    1093: ("ケイエスミラクル", "K.S. Miracle"),
    1094: ("ジャングルポケット", "Jungle Pocket"),
    1095: ("ビリーヴ", "Believe"),
    1096: ("ノーリーズン", "No Reason"),
    1097: ("スティルインラブ", "Still in Love"),
    1098: ("コパノリッキー", "Copano Rickey"),
    1099: ("ホッコータルマエ", "Hokko Tarumae"),
    1100: ("ワンダーアキュート", "Wonder Acute"),
    1101: ("サムソンビッグ", "Samson Big"),
    1102: ("サウンズオブアース", "Sounds of Earth"),
    1103: ("ロイスアンドロイス", "Royce and Royce"),
    1104: ("カツラギエース", "Katsuragi Ace"),
    1105: ("ネオユニヴァース", "Neo Universe"),
    1106: ("ヒシミラクル", "Hishi Miracle"),
    1107: ("タップダンスシチー", "Tap Dance City"),
    1108: ("ドゥラメンテ", "Duramente"),
    1109: ("ラインクラフト", "Rhein Kraft"),
    1110: ("シーザリオ", "Cesario"),
    1111: ("エアメサイア", "Air Messiah"),
    1112: ("デアリングハート", "Daring Heart"),
    1113: ("フサイチパンドラ", "Fusaichi Pandora"),
    1114: ("ブエナビスタ", "Buena Vista"),
    1115: ("オルフェーヴル", "Orfevre"),
    1116: ("ジェンティルドンナ", "Gentildonna"),
    1117: ("ウインバリアシオン", "Win Variation"),
    1118: ("アドマイヤグルーヴ", "Admire Groove"),
    1119: ("ドリームジャーニー", "Dream Journey"),
    1120: ("カルストンライトオ", "Calstone Light O"),
    1121: ("デュランダル", "Durandal"),
    1124: ("バブルガムフェロー", "Bubble Gum Fellow"),
    1126: ("サクラチトセオー", "Sakura Chitose O"),
    1127: ("フェノーメノ", "Fenomeno"),
    1128: ("ブラストワンピース", "Blast Onepiece"),
    1129: ("アーモンドアイ", "Almond Eye"),
    1130: ("ラッキーライラック", "Lucky Lilac"),
    1131: ("グランアレグリア", "Gran Alegria"),
    1132: ("ラヴズオンリーユー", "Loves Only You"),
    1133: ("クロノジェネシス", "Chrono Genesis"),
    1134: ("カレンブーケドール", "Curren Bouquetd'or"),
    1135: ("ステイゴールド", "Stay Gold"),
    1136: ("レッドディザイア", "Red Desire"),
    1137: ("キセキ", "Kiseki"),
    1138: ("フォーエバーヤング", "Forever Young"),
    1139: ("カジノドライヴ", "Casino Drive"),
    1140: ("マルシュロレーヌ", "Marche Lorraine"),
    1141: ("エピファネイア", "Epiphaneia"),
    1142: ("ロゴタイプ", "Logotype"),
    1143: ("ヴィクトワールピサ", "Victoire Pisa"),
    1144: ("ローズキングダム", "Rose Kingdom"),
    1145: ("ルーラーシップ", "Rulership"),
    1146: ("エフフォーリア", "Efforia"),
    1148: ("タイトルホルダー", "Titleholder"),
    1149: ("ファレノプシス", "Phalaenopsis"),
    2001: ("ハッピーミーク", "Happy Meek"),
    2002: ("ビターグラッセ", "Bitter Glasse"),
    2003: ("リトルココン", "Little Cocon"),
    2004: ("モンジュー", "Montjeu"),
    2005: ("ヴェニュスパーク", "Venus Park"),
    2006: ("リガントーナ", "Rigauntona"),
    2007: ("ソノンエルフィー", "Sonon Elfie"),
    2008: ("ST-2", "ST-2"),
    9001: ("駿川たづな", "Tazuna Hayakawa"),
    9002: ("秋川理事長", "Chairwoman Akikawa"),
    9003: ("乙名史記者", "Reporter Otonashi"),
    9004: ("桐生院トレーナー", "Trainer Kiryuin"),
    9005: ("安心沢刺々美", "Sasami Anshinzawa"),
    9006: ("樫本理子", "Riko Kashimoto"),
    9007: ("ビューティー安心沢", "Beauty Anshinzawa"),
    9008: ("ライトハロー", "Light Hello"),
    9040: ("ダーレーアラビアン", "Darley Arabian"),
    9041: ("ゴドルフィンバルブ", "Godolphin Barb"),
    9042: ("バイアリーターク", "Byerley Turk"),
    9043: ("佐岳メイ", "Mei Satake"),
    9044: ("都留岐涼花", "Ryoka Tsurugi"),
    9045: ("シュガーライツ", "Sugar Lights"),
    9046: ("セントライト", "St Lite"),
    9047: ("スピードシンボリ", "Speed Symboli"),
    9048: ("ハイセイコー", "Haiseiko"),
    9049: ("タッカーブライン", "Tucker Brine"),
    9050: ("保科健子", "Takeshi Hoshina"),
    9051: ("ユノハナブルーム", "Yunohana Bloom")
}

vb = json.load(open(r"G:\Games\steamapps\common\UmamusumePrettyDerby_Jpn\gemini_horses\tools\voice_bible\uma_voice_bible.json", encoding="utf-8"))

mismatches = []
for cid, (jp, cname) in canonical_names.items():
    s_cid = str(cid)
    v_en = vb.get(s_cid, {}).get("en")
    if v_en != cname:
        mismatches.append((cid, jp, v_en, cname))

print(f"Total mismatches against canonical names: {len(mismatches)}")
for cid, jp, v_en, cname in mismatches:
    print(f"ID {cid} [{jp}]: Current='{v_en}' -> Canonical='{cname}'")
