import sqlite3, json
conn = sqlite3.connect(r'C:\Users\Ota\.omniroute\storage.sqlite')
cur = conn.cursor()
cur.execute("SELECT value FROM key_value WHERE namespace='compression' AND key='outputStyles'")
row = cur.fetchone()
print('BEFORE:', row[0] if row else 'None')
cur.execute("INSERT OR REPLACE INTO key_value (namespace, key, value) VALUES ('compression', 'outputStyles', '[]')")
conn.commit()
cur.execute("SELECT value FROM key_value WHERE namespace='compression' AND key='outputStyles'")
print('AFTER:', cur.fetchone()[0])
conn.close()
print('outputStyles cleared')
